
let data;const $=id=>document.getElementById(id);const fmt=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(n);const names={seasonal_naive:'Seasonal naive',random_forest:'Random Forest',gradient_boosting:'Gradient boosting',sarima:'SARIMA'};
function tableRow(values){const tr=document.createElement('tr');values.forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.appendChild(td)});return tr}
function chart(target,series){const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 1000 310');svg.setAttribute('role','img');svg.setAttribute('aria-label',target==='history-chart'?'Historical ridership and future forecast':'Actual and predicted test-period ridership');const dates=[...new Set(series.flatMap(s=>s.points.map(p=>p.date)))].sort(),values=series.flatMap(s=>s.points.map(p=>p.value)).filter(Number.isFinite),max=Math.max(1,...values)*1.1;const x=d=>75+dates.indexOf(d)/Math.max(1,dates.length-1)*900,y=v=>270-v/max*235;
function el(tag,attrs,text){let e=document.createElementNS(ns,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));if(text!==undefined)e.textContent=text;svg.appendChild(e);return e}
for(let i=0;i<=4;i++){let v=max*i/4;el('line',{x1:75,x2:975,y1:y(v),y2:y(v),stroke:'#e3eae3'});el('text',{x:65,y:y(v)+4,'text-anchor':'end',fill:'#63736a','font-size':12},(v/1e6).toFixed(1)+'m')}
[...new Set([0,Math.floor((dates.length-1)/2),dates.length-1])].forEach(i=>el('text',{x:x(dates[i]),y:297,'text-anchor':'middle',fill:'#63736a','font-size':12},dates[i].slice(0,7)));
series.forEach(s=>{const points=s.points.filter(p=>Number.isFinite(p.value));el('polyline',{points:points.map(p=>`${x(p.date)},${y(p.value)}`).join(' '),fill:'none',stroke:s.color,'stroke-width':2.5,'stroke-dasharray':s.dashed?'6 4':'none'});points.forEach(p=>{let dot=el('circle',{cx:x(p.date),cy:y(p.value),r:3,fill:s.color});let title=document.createElementNS(ns,'title');title.textContent=`${p.date.slice(0,7)}: ${fmt(p.value)} trips`;dot.appendChild(title)})});$(target).replaceChildren(svg)}
function draw(){const history=data.history.slice(-Number($('range').value)),last=history.at(-1);chart('history-chart',[{color:'#195b42',points:history.map(r=>({date:r.date,value:r.ridership}))},{color:'#ce7534',dashed:true,points:[{date:last.date,value:last.ridership},...data.forecast.map(r=>({date:r.date,value:r.prediction}))]}]);chart('test-chart',[['actual','#195b42'],['prediction','#ce7534'],['seasonal_naive','#7d85a0']].map(([key,color])=>({color,points:data.test.map(r=>({date:r.date,value:r[key]}))})));}
async function load(){ $('error').textContent='';$('status').textContent='Loading saved results…';$('refresh').disabled=true;try{const response=await fetch('/results');const body=await response.json();if(!response.ok)throw Error(body.detail||'Could not load results.');data=body;const m=data.metadata;$('subtitle').textContent=`${m.agency} · ${m.mode}/${m.tos} · ${m.rows} monthly observations`;$('winner').textContent=names[m.selected_model];$('validation').textContent=`${m.horizon}-month forecasts · 3 validation blocks`;$('mae').textContent=fmt(m.test_metrics.mae)+' trips';$('test-period').textContent=m.test_start.slice(0,7)+' to '+m.test_end.slice(0,7);$('average').textContent=fmt(data.forecast.reduce((s,r)=>s+r.prediction,0)/data.forecast.length);$('forecast-period').textContent=data.forecast[0].date.slice(0,7)+' to '+data.forecast.at(-1).date.slice(0,7);$('models').replaceChildren(...data.comparison.map(r=>tableRow([names[r.model]+(r.model===m.selected_model?' · selected':''),fmt(r.mae),fmt(r.rmse),r.wape_percent===null?'N/A':r.wape_percent.toFixed(1)+'%'])));$('forecast-rows').replaceChildren(...data.forecast.map(r=>tableRow([r.date.slice(0,7),fmt(r.prediction)])));$('baseline').textContent=`Seasonal-naive test MAE: ${fmt(m.test_baseline_metrics.mae)} trips. This test was evaluated only after choosing the model.`;$('excluded').textContent=Object.entries(m.excluded_models).map(([name,reason])=>`${names[name]} excluded: ${reason}`).join(' ');$('provenance').textContent=`Source: ${m.source}. History ends ${m.history_end}. ${m.upt_listed_estimate_months} months listed in this release's UPT estimate sheet.`;$('limitations').textContent=m.limitations;$('content').hidden=false;draw();$('status').textContent='Results generated '+new Date(m.created_utc).toLocaleString();}catch(e){$('content').hidden=true;$('status').textContent='Results unavailable';$('error').textContent=e.message}finally{$('refresh').disabled=false}}
$('refresh').addEventListener('click',load);$('range').addEventListener('change',()=>{if(data)draw()});load();
